export type AgentCapability =
  | 'Text Generation'
  | 'Rewrite'
  | 'Translate'
  | 'Summarize'
  | 'SEO'
  | 'Grammar'
  | 'Research'
  | 'Planning'
  | 'Classification'
  | 'JSON Output'
  | 'Vision'
  | 'Image Prompting'
  | 'Video Prompting'
  | 'Reasoning'
  | 'Function Calling'
  | 'Workflow'
  | 'Publishing'
  | 'Validation'
  | 'Coding';
